### Data preprocessing
- Cleaned dataset with missing values handled
- Encoded categorical features for model compatibility
- Created target variable representing 10-year mortality risk
- Prepared training and testing datasets for model development

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from lifelines import KaplanMeierFitter
from sklearn.linear_model import LogisticRegression

In [3]:
#Load data
DATA_PATH = r"C:\Users\HP\Desktop\BIA\Breast_Cancer_Risk_Prediction\Data\Breast Cancer METABRIC.csv"
df = pd.read_csv(DATA_PATH)
df.head()

,Patient ID,Age at Diagnosis,Type of Breast Surgery,Cancer Type,Cancer Type Detailed,Cellularity,Chemotherapy,Pam50 + Claudin-low subtype,Cohort,ER status measured by IHC,...,Overall Survival Status,PR Status,Radio Therapy,Relapse Free Status (Months),Relapse Free Status,Sex,3-Gene classifier subtype,Tumor Size,Tumor Stage,Patient's Vital Status
0,MB-0000,75.65,Mastectomy,Breast Cancer,Breast Invasive Ductal Carcinoma,NaN,No,claudin-low,1.0,Positve,...,Living,Negative,Yes,138.65,Not Recurred,Female,ER-/HER2-,22.0,2.0,Living
1,MB-0002,43.19,Breast Conserving,Breast Cancer,Breast Invasive Ductal Carcinoma,High,No,LumA,1.0,Positve,...,Living,Positive,Yes,83.52,Not Recurred,Female,ER+/HER2- High Prolif,10.0,1.0,Living
2,MB-0005,48.87,Mastectomy,Breast Cancer,Breast Invasive Ductal Carcinoma,High,Yes,LumB,1.0,Positve,...,Deceased,Positive,No,151.28,Recurred,Female,NaN,15.0,2.0,Died of Disease
3,MB-0006,47.68,Mastectomy,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Moderate,Yes,LumB,1.0,Positve,...,Living,Positive,Yes,162.76,Not Recurred,Female,NaN,25.0,2.0,Living
4,MB-0008,76.97,Mastectomy,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,High,Yes,LumB,1.0,Positve,...,Deceased,Positive,Yes,18.55,Recurred,Female,ER+/HER2- High Prolif,40.0,2.0,Died of Disease

In [5]:
#Data back-up
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      2509 non-null   object
 1   Age at Diagnosis                2498 non-null   float64
 2   Type of Breast Surgery          1955 non-null   object
 3   Cancer Type                     2509 non-null   object
 4   Cancer Type Detailed            2509 non-null   object
 5   Cellularity                     1917 non-null   object
 6   Chemotherapy                    1980 non-null   object
 7   Pam50 + Claudin-low subtype     1980 non-null   object
 8   Cohort                          2498 non-null   float64
 9   ER status measured by IHC       2426 non-null   object
 10  ER Status                       2469 non-null   object
 11  Neoplasm Histologic Grade       2388 non-null   float64
 12  HER2 status measured by SNP6    1980 non-null   object
 13  HER2 Status                     1980 non-null   object
 14  Tumor Other Histologic Subtype  2374 non-null   object
 15  Hormone Therapy                 1980 non-null   object
 16  Inferred Menopausal State       1980 non-null   object
 17  Integrative Cluster             1980 non-null   object
 18  Primary Tumor Laterality        1870 non-null   object
 19  Lymph nodes examined positive   2243 non-null   float64
 20  Mutation Count                  2357 non-null   float64
 21  Nottingham prognostic index     2287 non-null   float64
 22  Oncotree Code                   2509 non-null   object
 23  Overall Survival (Months)       1981 non-null   float64
 24  Overall Survival Status         1981 non-null   object
 25  PR Status                       1980 non-null   object
 26  Radio Therapy                   1980 non-null   object
 27  Relapse Free Status (Months)    2388 non-null   float64
 28  Relapse Free Status             2488 non-null   object
 29  Sex                             2509 non-null   object
 30  3-Gene classifier subtype       1764 non-null   object
 31  Tumor Size                      2360 non-null   float64
 32  Tumor Stage                     1788 non-null   float64
 33  Patient's Vital Status          1980 non-null   object
dtypes: float64(10), object(24)
memory usage: 666.6+ KB

,Age at Diagnosis,Cohort,Neoplasm Histologic Grade,Lymph nodes examined positive,Mutation Count,Nottingham prognostic index,Overall Survival (Months),Relapse Free Status (Months),Tumor Size,Tumor Stage
count,2498.000000,2498.000000,2388.000000,2243.000000,2357.000000,2287.000000,1981.000000,2388.000000,2360.000000,1788.000000
mean,60.420300,2.900320,2.412060,1.950513,5.578702,4.028787,125.244271,108.842487,26.220093,1.713647
std,13.032997,1.962216,0.649363,4.017774,3.967967,1.189092,76.111772,76.519494,15.370883,0.655307
min,21.930000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
25%,50.920000,1.000000,2.000000,0.000000,3.000000,3.048000,60.866667,40.560000,17.000000,1.000000
50%,61.110000,3.000000,3.000000,0.000000,5.000000,4.044000,116.466667,99.095000,22.410000,2.000000
75%,70.000000,4.000000,3.000000,2.000000,7.000000,5.040000,185.133333,167.640000,30.000000,2.000000
max,96.290000,9.000000,3.000000,45.000000,80.000000,7.200000,355.200000,384.210000,182.000000,4.000000

In [6]:
#Missing value
df.isnull().sum().sort_values(ascending=False)

3-Gene classifier subtype         745
Tumor Stage                       721
Primary Tumor Laterality          639
Cellularity                       592
Type of Breast Surgery            554
Inferred Menopausal State         529
Integrative Cluster               529
Hormone Therapy                   529
Pam50 + Claudin-low subtype       529
Chemotherapy                      529
PR Status                         529
HER2 Status                       529
Radio Therapy                     529
Patient's Vital Status            529
HER2 status measured by SNP6      529
Overall Survival (Months)         528
Overall Survival Status           528
Lymph nodes examined positive     266
Nottingham prognostic index       222
Mutation Count                    152
Tumor Size                        149
Tumor Other Histologic Subtype    135
Relapse Free Status (Months)      121
Neoplasm Histologic Grade         121
ER status measured by IHC          83
ER Status                          40
Relapse Free Status                21
Age at Diagnosis                   11
Cohort                             11
Patient ID                          0
Cancer Type Detailed                0
Cancer Type                         0
Oncotree Code                       0
Sex                                 0
dtype: int64

In [8]:
# numerical
num_cols = df.select_dtypes(include=['int64','float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# categorical
cat_cols = df.select_dtypes(include=['object']).columns
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

In [9]:
#Drop irrelevant column
df = df.drop(['Patient ID'], axis=1)

In [10]:
# Create event column (dead = 1, alive = 0)
df['event'] = (df['Overall Survival Status'] == 'Deceased').astype(int)

# Create time column
df['time'] = df['Overall Survival (Months)']

# Create 10-year mortality target
df['target_10yr'] = ((df['time'] <= 120) & (df['event'] == 1)).astype(int)

In [12]:
# Drop column safely
df = df.drop(columns=['Patient ID'], errors='ignore')

# Fill missing values
df = df.fillna(df.median(numeric_only=True))
df = df.fillna(df.mode().iloc[0])

# Encode categorical
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cat_cols = df.select_dtypes(include=['object']).columns

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [13]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = df.drop(['target_10yr','time','event'], axis=1)
y = df['target_10yr']

X_scaled = scaler.fit_transform(X)

In [14]:
#Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)